export const textVariants = {
     defaultS:{},
     textXs:{
          fontSize:12,
          lineHeight:16,
     },
     textSm:{
          fontSize:14,
          lineHeight:18,
     },
     textBase:{
          fontSize:16,
          lineHeight:24,
     },
     textLg:{
          fontSize:18,
          lineHeight:28,
     },
     textXl:{
          fontSize:20,
          lineHeight:32,
     },
     text2Xl:{
          fontSize:24,
          lineHeight:36,
     },
     text3Xl:{
          fontSize:36,
          lineHeight:40,
     },
}